language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --skip-lock
script:
  - pytest -vs --cov sms_gateway --cov-report term-missing tests
after_success:
  - coveralls
